### ISSUE TITLE
Switch to Intern

### ISSUE THREAD

**Issue by bitpshr** [kfranqueiro/dojo-smore#1]
In forking SitePen/dojo-smore to submit a PR for an OData store, I noticed the tests are still using DOH, which totally makes sense considering how new Intern is. 

I figured it would still be good to at least create a ticket to track the ultimate move to Intern. I'll probably start a branch off my own fork to begin this work myself since @kfranqueiro is stretched thin on dgrid.

**Comment by kfranqueiro** [comment]
I had debated not bothering with this since 2 of the 3 stores in dojo-smore have equivalent versions in dstore now and people should start using that, but I fixed an issue in here last week and ran the unit tests and remembered how much more I like Intern than DOH, so I went ahead and did this in https://github.com/kfranqueiro/dojo-smore/commit/5b21fa4e0ee28a52b9013d34e1c9859ddb328df8. :P

I removed the DOH performance tests that were in here before; they don't serve much point anymore anyway, they were mostly for evaluating during initial development.
